language: node_js
node_js:
  - lts/dubnium
os:
  - linux
dist: bionic
before_install:
  - curl -sL https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh -o install_nvm.sh
  - bash install_nvm.sh
  - command -v nvm
  - sudo apt-get update && sudo apt-get install
  - nvm install lts/dubnium && nvm use lts/dubnium
  - npm install -g node-gyp
cache:
  apt: true
jobs:
  include:
      # Linux
      - stage: build
        name: 'Test VGP NodeJS package build'
        script:
          - npm update; node-gyp clean; node-gyp configure; node-gyp build
          - node test.js
      - stage: install
        name: 'Test VGP NodeJS install'
        script:
          - npm install
          - node test.js